### ISSUE TITLE
Attack S and Attack P cant be reproduced

### ISSUE THREAD

**Issue by xjc1234567** [privacytrustlab/ml_privacy_meter#104]
Hi, I noticed that the detailed implementation of attack S and attack P was not given in the source code of Enhanced MIA, how can I find them？

**Comment by changhongyan123** [comment]
Hi @xjc1234567 ,

The attacks S and P are incorporated within the shadow_metric and population_metric modules respectively in the privacy meter. To gain a more detailed understanding of how these attacks are executed, please consult the files [shadow_metric.ipynb](https://github.com/privacytrustlab/ml_privacy_meter/blob/master/tutorials/shadow_metric.ipynb) and [population_metric.ipynb](https://github.com/privacytrustlab/ml_privacy_meter/blob/master/tutorials/population_metric.ipynb).

**Comment by yuan74** [comment]
Hi @xjc1234567, the hyperparameters for training the shadow models in attack S are the same as the hyperparameters for reference models in attack R. Additionally, an example for replicating attack P on cifar-10 in the table of the paper can be found here https://github.com/privacytrustlab/ml_privacy_meter/tree/master/benchmark
