### ISSUE TITLE
AttributeError: 'attack_data' object has no attribute 'means'

### ISSUE THREAD

**Issue by The-MinGo** [privacytrustlab/ml_privacy_meter#19]
Hello, there might be a trivial flaw in your code.

In line 39 of the file `ml_privacy_meter/tutorials/attack_alexnet.py`: 
![image](https://user-images.githubusercontent.com/50874957/102001356-69ee1c80-3d2c-11eb-9b21-055d2e06ee1e.png)
it is written that the means and standard deviations for normalization will be calculated if unset.

I understand that you expect this to be determined by this line in `ml_privacy_meter/tutorials/attack_alexnet.py`:
![image](https://user-images.githubusercontent.com/50874957/102001460-7de64e00-3d2d-11eb-97f4-0b22818d1562.png)

However, it doesn't work but instead introduces an error on my machine:
**AttributeError: 'attack_data' object has no attribute 'means'**

The fact that you didn't declare these two attributes (`means` and `stddevs`) in the initialization method of class `attack_data` is presumably the reason. So the bug crawled into your program.
![image](https://user-images.githubusercontent.com/50874957/102001620-1e893d80-3d2f-11eb-8fec-3fef60b8ad74.png)

Looking forward to your reply.

**Comment by mihirkhandekar** [comment]
Thanks for pointing out this issue. We will test it and fix the issue in the code accordingly.

**Comment by The-MinGo** [comment]
Hello, more information provided to help you:
The error shot me after this line of code was commented out.
![image](https://user-images.githubusercontent.com/50874957/102012126-7e113880-3d83-11eb-8dd7-7a10ee8fb2f8.png)
Since I hope your tool can help to calculate the means and standard deviations, instead of assign them like _hyperparameters_.

And I have a question:
**is your program an implementation of supervised training on shadow models?**
Namely, is model A a shadow model of model B?
![image](https://user-images.githubusercontent.com/50874957/102012072-4bffd680-3d83-11eb-8a7d-3bedc1d36952.png)

As the code shows me, it's assumed that a **subset** of the training set is known to the attacker
![image](https://user-images.githubusercontent.com/50874957/102012200-f7a92680-3d83-11eb-849d-dff21d673c7f.png)
 as well as some data from the same underlying distribution that is not contained in the training set.
![image](https://user-images.githubusercontent.com/50874957/102012234-245d3e00-3d84-11eb-962f-14213c706144.png)


![image](https://user-images.githubusercontent.com/50874957/102012282-74d49b80-3d84-11eb-81fb-b72f6e5086db.png)

Do I get it right? I'm sorry for my lack of expression.

**Comment by mihirkhandekar** [comment]
Thank you for providing the additional information. Model A can be used as a shadow model to evaluate the performance of your membership inference model on Model B.
Thank you for the diagram as well, it is a good representation of the data. However, I would like to point out that the non-member set does not have an intersection with the cifar100_train.txt.npy, since this file is only generated using the training data (Member set).

**Comment by The-MinGo** [comment]
I get that. It's my mistake. 
![image](https://user-images.githubusercontent.com/50874957/102013733-eca6c400-3d8c-11eb-9f0d-5189ccc42d80.png)
And thank you for your reply (*^_^*)
