### ISSUE TITLE
Question: What's the relationship between `target_train_model` and `target_attack_model`?

### ISSUE THREAD

**Issue by The-MinGo** [privacytrustlab/ml_privacy_meter#22]
@mihirkhandekar Hello, I'm still confused and sorry to trouble you again.
In the issue [#19](https://github.com/privacytrustlab/ml_privacy_meter/issues/19), you replied me that
> Model A (target_train_model) can be used as a shadow model to evaluate the performance of your membership inference model on Model B (target_attack_model).
- Do model A (target_train_model) and model B (target_attack_model) have the same architecture but different parameters?
- Or, are they completely different, just with the same classification task and dataset?

In the tutorials provided, you show me two examples. But in both of them, you pass the same model to `target_train_model` and `target_attack_model`, which really confuses me.
![image](https://user-images.githubusercontent.com/50874957/102713655-c6d96c00-4304-11eb-8dd6-f181cc717f64.png)
![image](https://user-images.githubusercontent.com/50874957/102713675-f0929300-4304-11eb-8c6f-6472870a4fba.png)

In the file `ml_privacy_meter/attack/meminf.py `, the handling of `target_attack_model` stops at receiving it. And no further operation.
![image](https://user-images.githubusercontent.com/50874957/102713713-246db880-4305-11eb-906e-aee7c5ecd42d.png)

As for the method `test_attack()`, I'm not sure what role it plays in your blueprint.
Is it a mistake that `self.target_train_model` should be replaced with `self.target_attack_model` to evaluate the performance of membership inference model on Model B (target_attack_model)?
![image](https://user-images.githubusercontent.com/50874957/102713731-46ffd180-4305-11eb-8234-642060508d1c.png)

Expect receiving your reply.

**Comment by mihirkhandekar** [comment]
Thank you. Will take a look and let you know.

**Comment by tr0p1x** [comment]
I am facing one more error still related to passing `target_train_model` and `target_attack_model` as two different datahandlers:

> AttributeError: 'attack_data' object has no attribute 'nonmember_train'

Error is raised by line no. 202 of `ml_privacy_meter/utils/attack_data.py`:

> `nmtrainhashes = compute_hashes(self.nonmember_train)`

That is problably due to `self.nonmember_train` being initialized by the `load_train()` method, which is actually not invoked on the `target_attack_model` datahandler.

**Comment by PAODAZHANG** [comment]
> 

This question which had been taked by @gongzhimin  at issue #22 confuses me too。 could you please explain it to us？
