### ISSUE TITLE
OOM problem in attack alexnet

### ISSUE THREAD

**Issue by detaimee** [privacytrustlab/ml_privacy_meter#32]
Hi.
When I run the alexnet.py code to create the model and then run the attack_alexnet.py code, I have an oom problem, so I ask a question.
First of all, my setting environment was run with rtx 2080ti and I used tensorflow-gpu version 2.1.0 as in requirements.txt.
So what I want to ask is
1. What setting environment was used to run the code, and I am curious about the minimum graphic specification or graphic memory to execute the code.
2. I am curious to know which variables need to be changed in order to be executed properly with the current graphics card.

Thanks in advance.

<img width="1351" alt="스크린샷 2021-03-17 오후 8 01 16" src="https://user-images.githubusercontent.com/65382643/111457463-91091f80-875b-11eb-8430-51579c626d84.png">

**Comment by amad-person** [comment]
Hi @detaimee, you can try to reduce the batch sizes for training/testing datasets. I also found this [stackoverflow question ](https://stackoverflow.com/questions/42495930/tensorflow-oom-on-gpu)that has some other approaches you can try.
