### ISSUE TITLE
feberated learning

### ISSUE THREAD

**Issue by intefirm** [privacytrustlab/ml_privacy_meter#35]
Hi, I would like to know how this library should be used on a federal learning scenario? Also, how should I be able to reproduce your  attacks on federated learning described on your paper " Comprehensive Privacy Analysis of Deep Learning: Stand-alone and Federated Learning under Passive and Active White-box Inference Attacks" ？I would appreciate a lot if you could reply promptly.

**Comment by amad-person** [comment]
@intefirm Currently, ML Privacy Meter doesn’t support running experiments in the federated learning setting. 

However, I can point you to the code used for the paper: https://github.com/SPIN-UMass/MembershipWhiteboxAttacks/blob/master/ATTACK-ALEXNET-grad_fed_local.py
