### ISSUE TITLE
pip install -r requirements.txt throws: ERROR: No matching distribution found for tensorflow-gpu==2.5.0

### ISSUE THREAD

**Issue by chris-prenode** [privacytrustlab/ml_privacy_meter#41]
Hello together,

I tried to install this project again and the described setup doesn't work anymore.
I installed `Python 3.6.13` in my Anaconda environment with following packages using the `pip install -r requirements.txt` command. 
[conda_list.txt](https://github.com/privacytrustlab/ml_privacy_meter/files/6554788/conda_list.txt) attached.

But it throws in the end:
`ERROR: No matching distribution found for tensorflow-gpu==2.5.0`

```
(dt_test) Admins-MacBook-Pro:ml_privacy_meter christianstudinsky$ pip install -r requirements.txt

....
Requirement already satisfied: scipy==1.4.1 in /Users/christianstudinsky/opt/anaconda3/envs/dt_test/lib/python3.6/site-packages (from -r requirements.txt (line 39)) (1.4.1)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting sklearn==0.0
  Using cached sklearn-0.0-py2.py3-none-any.whl
Requirement already satisfied: tensorboard==2.1.1 in /Users/christianstudinsky/opt/anaconda3/envs/dt_test/lib/python3.6/site-packages (from -r requirements.txt (line 42)) (2.1.1)
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.5.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for tensorflow-gpu==2.5.0
```

**Comment by amad-person** [comment]
Hi, please use tensorflow 2.1.0 and python 3.6 as stated in the README. 

The dependabot pull requests automatically updated the dependencies, I will change the tensorflow version in the requirements.txt file.
