### ISSUE TITLE
can i attack linear regression、logistic、XGBoost models?

### ISSUE THREAD

**Issue by yangshaojie0123** [privacytrustlab/ml_privacy_meter#47]
1)how can i attack these models?
2)can i attack some models like scikit-learn.job joblib?

**Comment by amad-person** [comment]
Hi @yangshaojie0123, you can attack linear/logistic regression models by using a single layer `Sequential` model ([example](https://www.tensorflow.org/tutorials/keras/regression#linear_regression) on tensorflow docs). You'll need to pass tensorflow models to the tool if I'm not wrong. I am not sure if boosted trees
