### ISSUE TITLE
Code of "MIA via Distillation"

### ISSUE THREAD

**Issue by jlyang1990** [privacytrustlab/ml_privacy_meter#62]
Hi, I'm reading the paper [Enhanced Membership Inference Attacks against Machine Learning Models](https://arxiv.org/pdf/2111.09679.pdf). It is very well written! I'm wondering if you have plan to open-source the code of "MIA via Distillation", since "MIA via Distillation" is claimed to have better performance than other MIAs already implemented in this package. I'm very interested in the algorithm/implementation details of this attack. Thanks!

**Comment by changhongyan123** [comment]
@jlyang1990 , the code is available now. You can find it in the [attack_via_reference_or_distill.ipynb](https://github.com/privacytrustlab/ml_privacy_meter/blob/master/research/2022_enhanced_mia/attack_via_reference_or_distill.ipynb).
