### ISSUE TITLE
Request for FL and Unsupervised Learning Version

### ISSUE THREAD

**Issue by akyo1o** [privacytrustlab/ml_privacy_meter#79]
Will you develop versions based on Federated Learning and Unsupervised Learning in the future? I am very interested in your articles.

**Comment by changhongyan123** [comment]
@akyo1o , That are definitely good directions for improving our privacy meter. In terms of federated learning, you can check the [paper](https://www.comp.nus.edu.sg/~reza/files/Shokri-SP2019.pdf), which proposes attack algorithms for the FL.
