### ISSUE TITLE
Old tutorials with restructured code 

### ISSUE THREAD

**Issue by nitincic** [privacytrustlab/ml_privacy_meter#81]
There are some tutorial in the archive folder from the earlier version of the library which work for whitebox attacks (exposing gradients etc). I don't see similar options with the restructured code. Is it still possible to audit those attacks or have those attacks been renamed?

**Comment by changhongyan123** [comment]
Hi @nitincic , thank you for your question. The restructured code does not provide examples of the white-box attacks. However, you can specify how to get the gradient information (e.g., PyTorch) in the [model.py](https://github.com/privacytrustlab/ml_privacy_meter/blob/master/privacy_meter/model.py#L86) and define your own Metric, which infers members using the ModelGradient. For example, you can replace ModelLoss in [audit.py](https://github.com/privacytrustlab/ml_privacy_meter/blob/1fe6f183a232cfdcdcf1c9a9b7830dd8505376d2/privacy_meter/audit.py#L86). We will provide white-box attack examples using restructured code soon.
