### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [privacytrustlab/ml_privacy_meter#82]
It would be great to have a conda recipe so that it can be included with projects that have more complicated build processes (for example, using libraries that need C/C++ compilers).

**Comment by changhongyan123** [comment]
Thank you so much @sarthakpati, for your contribution. We really appreciate it! I will test it and merge the pull request.

**Comment by changhongyan123** [comment]
Hi @sarthakpati , I encountered the following issues:

**Comment by changhongyan123** [comment]
Hi @sarthakpati , I encountered the following issues. Do you have any ideas about solving this issue?

```bash
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
  - defaults/osx-64::scikit-learn==0.24.1=py38hb2f4e1b_0
  - defaults/osx-64::scikit-image==0.18.1=py38hb2f4e1b_0
  - defaults/osx-64::patsy==0.5.1=py38_0
  - defaults/osx-64::astropy==4.2.1=py38h9ed2024_1
  - defaults/osx-64::anaconda==2021.05=py38_0
  - defaults/noarch::seaborn==0.11.1=pyhd3eb1b0_0
  - defaults/osx-64::statsmodels==0.12.2=py38h9ed2024_0
```

**Comment by changhongyan123** [comment]
Thank you for your prompt reply. I solved the problem. Previously, I tested on conda env of version 4.10.3. When testing on conda env 4.12.0, privacy-meter can be installed correctly.

Thank you so much for your contribution :)! I will forward this pull request to the repository admin.
