### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../privacy_meter/report_files/explanations.json'

### ISSUE THREAD

**Issue by sebasrb09** [privacytrustlab/ml_privacy_meter#90]
In order to plot the ROCCurveReport, it is needed a explanations.json file. But it is never created and therefore, the report crashes. I'm trying 

```
ROCCurveReport.generate_report(`
    metric_result=audit_results,
    inference_game_type=InferenceGame.PRIVACY_LOSS_MODEL,
    show=True
)
```

**Comment by changhongyan123** [comment]
Hi @sebasrb09, the explanations.json file is included in our repository and you don't need to generate it. See:
https://github.com/privacytrustlab/ml_privacy_meter/blob/master/privacy_meter/report_files/explanations.json

Can you check if you installed the privacy meter correctly and if the file exists in the local version of the privacy meter?

**Comment by sebasrb09** [comment]
Hi! I installed it with pip in an anaconda environment and the file does not exist in the local version. But I had not found it, I will add it manually to my local version.
